spring:
  application:
    name: demo
  mvc:
    problemdetails:
      enabled: true

okta:
  oauth2:
    issuer: https://dev-39430131.okta.com/oauth2/default
    client-id: 0oadauximdO4VWG7z5d7
    client-secret: ${OKTA_CLIENT_SECRET}
    redirect-uri: /authorization-code/callback
