spring:
  application:
    name: demo
  mvc:
    problemdetails:
      enabled: true

okta:
  oauth2:
    issuer: https://gigiyy.us.auth0.com/
    client-id: 55kpIaPxO05NCX6eRhVjxYH95AgDztUH
    client-secret: ${AUTH0_CLIENT_SECRET}
    redirect-uri: /login/oauth2/code/okta
